#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
on-launch_nointeract-preflight  —  bulk-operation guard for non-interactive clients.

When TW_NOINTERACT=1, detects mutating commands that would affect more tasks
than the configured threshold and exits non-zero with a structured JSON signal
on stderr so the client can present a confirmation UI before proceeding.

Environment variables (set by the calling client):
  TW_NOINTERACT=1            — activate this hook (any non-terminal client)
  TW_PREFLIGHT_CONFIRMED=1   — skip check; client already obtained confirmation
  TW_PREFLIGHT_VERB=modify   — the command verb (modify/delete/done/start/…)
  TW_PREFLIGHT_FILTER=…      — filter tokens (space-separated, shlex-safe)
  TW_PREFLIGHT_CMD=…         — full original command string (for display only)
  TW_PREFLIGHT_THRESHOLD=3   — task count above which to block (default: 3)

On block, writes to stderr (one JSON line):
  {"type":"tw_preflight","count":N,"verb":"…","filter":"…","cmd":"…"}
and exits 1.  Taskwarrior aborts the command; the client parses the signal.

On pass (count ≤ threshold, confirmed, or non-interactive not active): exits 0.
"""

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
import json
import shlex
import subprocess

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    """Log dir respects TW_TASK_DIR for dev/test isolation."""
    import os as _os
    task_dir = Path(_os.environ.get('TW_TASK_DIR', str(Path.home() / '.task')))
    log_dir = task_dir / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

def main():
    # Only act for non-interactive clients
    if not os.environ.get('TW_NOINTERACT'):
        sys.exit(0)

    # Client already confirmed — step aside
    if os.environ.get('TW_PREFLIGHT_CONFIRMED'):
        sys.exit(0)

    verb       = os.environ.get('TW_PREFLIGHT_VERB', '').strip()
    filter_str = os.environ.get('TW_PREFLIGHT_FILTER', '').strip()
    cmd_str    = os.environ.get('TW_PREFLIGHT_CMD', '').strip()

    # Nothing to evaluate
    if not verb or not filter_str:
        sys.exit(0)

    try:
        threshold = int(os.environ.get('TW_PREFLIGHT_THRESHOLD', '3'))
    except ValueError:
        threshold = 3

    # Count tasks matching the filter — hooks off so we don't recurse
    try:
        filter_args = shlex.split(filter_str)
        result = subprocess.run(
            ['task', 'rc.hooks=off', 'rc.verbose=nothing'] + filter_args + ['count'],
            capture_output=True, text=True, timeout=5
        )
        count = int(result.stdout.strip()) if result.returncode == 0 else 0
    except Exception:
        sys.exit(0)  # on any error, don't block — fail open

    if count > threshold:
        signal = {
            'type':      'tw_preflight',
            'count':     count,
            'verb':      verb,
            'filter':    filter_str,
            'cmd':       cmd_str,
            'threshold': threshold,
        }
        print(json.dumps(signal), file=sys.stderr)
        sys.exit(1)

    sys.exit(0)

main()
